# Generated by Django 4.0.3 on 2022-03-31 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_profile_delete_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Follow',
        ),
    ]
