# Generated by Django 4.0.3 on 2022-03-31 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_follow_follower_follow_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='follow_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follow_followwing', to=settings.AUTH_USER_MODEL),
        ),
    ]
