# Generated by Django 4.0.3 on 2022-03-31 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_follow_followers_follow_followings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followings',
        ),
    ]
