# Generated by Django 4.0.3 on 2022-03-31 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_user_follower_delete_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follower',
            new_name='follow',
        ),
    ]
