# Generated by Django 4.0.3 on 2022-03-31 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_remove_user_followingss_user_follower_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
